# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "flat_ui"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["dalphen"]
  s.date = "2013-04-11"
  s.description = "FlatUi wraps and installs the free version of Flat UI into a rails asset pipeline."
  s.email = "dalphen@reorientgroup.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/fonts/flat_ui/Flat-UI-Icons-16.dev.svg",
    "app/assets/fonts/flat_ui/Flat-UI-Icons-16.eot",
    "app/assets/fonts/flat_ui/Flat-UI-Icons-16.svg",
    "app/assets/fonts/flat_ui/Flat-UI-Icons-16.ttf",
    "app/assets/fonts/flat_ui/Flat-UI-Icons-16.woff",
    "app/assets/fonts/flat_ui/Flat-UI-Icons-24.dev.svg",
    "app/assets/fonts/flat_ui/Flat-UI-Icons-24.eot",
    "app/assets/fonts/flat_ui/Flat-UI-Icons-24.svg",
    "app/assets/fonts/flat_ui/Flat-UI-Icons-24.ttf",
    "app/assets/fonts/flat_ui/Flat-UI-Icons-24.woff",
    "app/assets/images/bag.png",
    "app/assets/images/block-off.png",
    "app/assets/images/block-on.png",
    "app/assets/images/book.png",
    "app/assets/images/calendar.png",
    "app/assets/images/checkbox-2x.png",
    "app/assets/images/checkbox.png",
    "app/assets/images/clipboard.png",
    "app/assets/images/colors.png",
    "app/assets/images/compass.png",
    "app/assets/images/done-2x.png",
    "app/assets/images/done.png",
    "app/assets/images/favicon.ico",
    "app/assets/images/fullscreen-2x.png",
    "app/assets/images/fullscreen.png",
    "app/assets/images/gift.png",
    "app/assets/images/icon-off-2x.png",
    "app/assets/images/icon-off.png",
    "app/assets/images/icon-on-2x.png",
    "app/assets/images/icon-on.png",
    "app/assets/images/icon.png",
    "app/assets/images/imac-2x.png",
    "app/assets/images/imac.png",
    "app/assets/images/infinity.png",
    "app/assets/images/mail.png",
    "app/assets/images/map.png",
    "app/assets/images/next.png",
    "app/assets/images/paper.png",
    "app/assets/images/pause-2x.png",
    "app/assets/images/pause.png",
    "app/assets/images/play-2x.png",
    "app/assets/images/play.png",
    "app/assets/images/previous.png",
    "app/assets/images/radio-2x.png",
    "app/assets/images/radio.png",
    "app/assets/images/retina.png",
    "app/assets/images/search-2x.png",
    "app/assets/images/search.png",
    "app/assets/images/share.png",
    "app/assets/images/time.png",
    "app/assets/images/todo-2x.png",
    "app/assets/images/todo.png",
    "app/assets/images/toggle.png",
    "app/assets/images/volume-full-2x.png",
    "app/assets/images/volume-full.png",
    "app/assets/images/volume-off-2x.png",
    "app/assets/images/volume-off.png",
    "app/assets/javascripts/flat_ui/application.js",
    "app/assets/javascripts/flat_ui/bootstrap-tooltip.js",
    "app/assets/javascripts/flat_ui/custom_checkbox_and_radio.js",
    "app/assets/javascripts/flat_ui/custom_radio.js",
    "app/assets/javascripts/flat_ui/html5shiv.js",
    "app/assets/javascripts/flat_ui/icon-font-ie7.js",
    "app/assets/javascripts/flat_ui/jquery-1.8.2.min.js",
    "app/assets/javascripts/flat_ui/jquery-ui-1.10.0.custom.min.js",
    "app/assets/javascripts/flat_ui/jquery.dropkick-1.0.0.js",
    "app/assets/javascripts/flat_ui/jquery.placeholder.js",
    "app/assets/javascripts/flat_ui/jquery.tagsinput.js",
    "app/assets/javascripts/flat_ui/lte-ie7-24.js",
    "app/assets/stylesheets/flat_ui/_config.sass",
    "app/assets/stylesheets/flat_ui/_icon-font-24.sass",
    "app/assets/stylesheets/flat_ui/_icon-font.sass",
    "app/assets/stylesheets/flat_ui/_mixins.sass",
    "app/assets/stylesheets/flat_ui/_spaces.sass",
    "app/assets/stylesheets/flat_ui/flat-ui.sass",
    "app/assets/stylesheets/flat_ui/modules/_btn.sass",
    "app/assets/stylesheets/flat_ui/modules/_checkbox-and-radio.sass",
    "app/assets/stylesheets/flat_ui/modules/_footer.sass",
    "app/assets/stylesheets/flat_ui/modules/_input.sass",
    "app/assets/stylesheets/flat_ui/modules/_login.sass",
    "app/assets/stylesheets/flat_ui/modules/_navbar.sass",
    "app/assets/stylesheets/flat_ui/modules/_pager.sass",
    "app/assets/stylesheets/flat_ui/modules/_pagination.sass",
    "app/assets/stylesheets/flat_ui/modules/_palette.sass",
    "app/assets/stylesheets/flat_ui/modules/_progress.sass",
    "app/assets/stylesheets/flat_ui/modules/_select.sass",
    "app/assets/stylesheets/flat_ui/modules/_share.sass",
    "app/assets/stylesheets/flat_ui/modules/_tag-it.sass",
    "app/assets/stylesheets/flat_ui/modules/_tagsinput.sass",
    "app/assets/stylesheets/flat_ui/modules/_todo.sass",
    "app/assets/stylesheets/flat_ui/modules/_toggle.sass",
    "app/assets/stylesheets/flat_ui/modules/_tooltip.sass",
    "app/assets/stylesheets/flat_ui/modules/_type.sass",
    "app/assets/stylesheets/flat_ui/modules/_ui-slider.sass",
    "app/assets/stylesheets/flat_ui/modules/_video.sass",
    "flat_ui.gemspec",
    "lib/flat_ui.rb",
    "lib/flat_ui/engine.rb"
  ]
  s.homepage = "http://github.com/reorient/flat_ui"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "FlatUi wraps and installs the free version of Flat UI into a rails asset pipeline."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

